/// Flutter icons MyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData mail = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled_alt = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_alt = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_bold = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_bold = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_bold = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_bold = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_fat = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_fat = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_fat = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_fat = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_pencil = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData king = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anchor = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_open = IconData(0xf005, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xf006, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_open = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = IconData(0xf009, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb = IconData(0xf00a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_thumb_empty = IconData(0xf00b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coverflow = IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coverflow_empty = IconData(0xf00d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xf00e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xf00f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_end = IconData(0xf010, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start = IconData(0xf011, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xf012, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = IconData(0xf013, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_cloud = IconData(0xf014, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cloud = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_science = IconData(0xf016, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_science_inv = IconData(0xf017, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xf018, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_inv = IconData(0xf019, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math = IconData(0xf01a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math_circled_empty = IconData(0xf01b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData math_circled = IconData(0xf01c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xf01d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_alt2 = IconData(0xf01e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_alt = IconData(0xf01f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_adjust = IconData(0xf020, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half = IconData(0xf022, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half_empty = IconData(0xf024, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ccw = IconData(0xf025, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_broken = IconData(0xf028, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hash = IconData(0xf029, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = IconData(0xf02a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retweet = IconData(0xf02b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xf02c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xf02e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xf02f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xf031, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monitor = IconData(0xf032, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet = IconData(0xf033, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xf034, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connected_object = IconData(0xf035, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData isight = IconData(0xf039, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = IconData(0xf03a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle = IconData(0xf03b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xf03d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf03f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xf040, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler = IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xf045, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_off = IconData(0xf047, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xf048, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xf04a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble_circled = IconData(0xf04f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble = IconData(0xf050, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_circled = IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf052, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled_alt = IconData(0xf053, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled_1 = IconData(0xf054, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf055, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled_alt2 = IconData(0xf056, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_circled = IconData(0xf057, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus_circled = IconData(0xf059, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gplus = IconData(0xf05a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_circled = IconData(0xf05b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf05c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf05d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_circled = IconData(0xf05e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mfg_logo = IconData(0xf05f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mfg_logo_circled = IconData(0xf060, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf061, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_male = IconData(0xf062, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_female = IconData(0xf063, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xf064, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xf067, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open = IconData(0xf068, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = IconData(0xf069, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xf06a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xf06d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled = IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox = IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xf074, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_alt = IconData(0xf075, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xf07b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in = IconData(0xf07e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out = IconData(0xf07f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xf080, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xf081, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf083, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd = IconData(0xf084, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled_alt = IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xf087, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fontsize = IconData(0xf088, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = IconData(0xf089, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud_circled = IconData(0xf08a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xf4ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_empty = IconData(0xf4c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xf4c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xf4f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xf4f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xf50d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_alt = IconData(0xf510, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xf512, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xf513, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joystick = IconData(0xf514, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spread = IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner1 = IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinner2 = IconData(0xf529, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
